### ISSUE TITLE
issue with the dataset

### ISSUE THREAD

**Issue by Mathew-Scott578** [mitul-garg/stutter-classification#2]
![git_issue](https://github.com/mitul-garg/stutter-classification/assets/172782453/9a7a7335-e172-4e32-a430-ae37475d6eae)

i was trying to run your code but i was confused in this part, the dataset provided by you didn't have a file named 'HeStutters_0_9.wav' for me to remove, i would greatly appreciate it if you could help me out in this one :)

**Comment by mitul-garg** [comment]
Hi, if you are using the dataset named SEP-28K MFCC, then it has all the empty files already removed from it. You can skip this step in that case.
